### 添加用户
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test.qq.com",
  "password": "123456"
}

### 获取验证码
GET http://localhost:3000/login


### 登录
POST http://localhost:3000/login
Content-Type: application/json

{
  "name": "admin",
  "password": "123456"
}

